### PR TITLE
fix insert not respecting defaluts and not nulls

### LINKED ISSUE #33: sql:insert doesn't respect default values
When a schema defines default values, the current implementation doesn't respect that and somehow endup inserting null in those fields instead.

Example: 

```sql 
create table if not exists test(
  id integer primary key,
  title text not null,
  created datetime default current_timestamp,
)
```

### PR DESCRIPTION
**Pull request by tami5**
closes #33

### CODE REVIEW

File: lua/sql.lua [hunk 1]
```diff
@@ -235,17 +235,42 @@ end
...
+      }
+    end
+
+    for k, v in pairs(tbl_info) do
+      if v.required then
+        req[k] = v
+      elseif v.default then
+        def[k] = v.default
+      end
+      types[k] = v.type
```
Comment (Conni2461) [inline lua/sql.lua:265]: Why not doing that the first time `tbl_sch` is iterated? You can just fill those tables as well? Can't we?

Comment (tami5) [reply lua/sql.lua:265]: indeed, yah I can merge them together, good catch
